[11.0][IMP]ao_sale lines to invoice
ForgeFlow/ao-odoo pull request #102
Opened 2019-02-19 16:37 UTC by aheficent

Solves 21017

Not sure if putting the code in separate module.

2019-02-25 11:44 UTC, HviorForgeFlow requested changes

2019-02-25 11:44 UTC, hveficent commented on ao_sale/migrations/11.0.2.1.0/pre-migration.py
> +        AND pt.service_type = 'manual')
@aheficent Remove last )

2019-02-25 11:46 UTC, hveficent commented
Solving 21017 but also 20840 ???

2019-02-25 12:35 UTC, hveficent commented on ao_sale/migrations/11.0.2.1.0/pre-migration.py
> +        AND pt.service_type = 'manual')
@aheficent not that sorry, last in this line :smile:

2019-02-25 12:45 UTC, aheficent commented
> 20840
No. We have to set them manually as delivered. But I think this is a configuration problem in the product. If they don't want to deliver, why don't set the product as "invoice in ordered quantities"?

Perhaps

2019-02-26 10:38 UTC, HviorForgeFlow approved these changes
LGTM :+1: Squash commits needed

2019-06-06 10:33 UTC, merged