change @class in expr for hasclass due to WARNING Error-prone use of …
ForgeFlow/ao-odoo pull request #60
Opened 2018-11-02 11:32 UTC by hveficent

…@class in view

2018-11-02 15:47 UTC, jbeficent commented
@hveficent this is failing

2018-11-15 15:12 UTC, MiquelRForgeFlow requested changes

2018-11-15 15:12 UTC, mreficent commented on ao_mrp/views/mrp_production_report.xml
> +        <xpath expr="//div[hasclass('row mt32 mb32')][1]" position="inside">
-> hasclass('row', 'mt32', 'mb32')

2018-11-15 15:12 UTC, mreficent commented on ao_purchase/views/report_purchase_order.xml
> +        <xpath expr="//div[hasclass('page')]/div[2]/div[1]" position="replace">
remove this as I already did it in https://github.com/Eficent/ao-odoo/pull/71

2018-11-15 15:12 UTC, mreficent commented on ao_purchase/views/report_purchase_order.xml
> +        <xpath expr="//div[hasclass('page')]/div[2]/div[1]" position="replace">
also remove this

2018-11-15 15:59 UTC, mreficent commented
Superseeded by https://github.com/Eficent/ao-odoo/pull/71.

2018-11-15 15:59 UTC, closed without merging